Cakeful/Models/Order.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;

namespace Cakeful.Models
{
    public class Order
    {
        [BindNever]
        public int OrderId { get; set; }

        public List<OrderDetail>? OrderDetails { get; set; }

        [Required(ErrorMessage = "Please enter your first name")]
        [Display(Name = "First name")]
        [StringLength(50)]
        public string FirstName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter your last name")]
        [Display(Name = "Last name")]
        [StringLength(50)]
        public string LastName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter your address")]
        [StringLength(100)]
        [Display(Name = "Address Line 1")]
        public string AddressLine1 { get; set; } = string.Empty;

        [Display(Name = "Address Line 2")]
        public string? AddressLine2 { get; set; }

        [Required(ErrorMessage = "Please enter your zip code")]
        [Display(Name = "Zip code")]
        [StringLength(10, MinimumLength = 4)]
        public string ZipCode { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter your city")]
        [StringLength(50)]
        public string City { get; set; } = string.Empty;

        [StringLength(10)]
        public string? State { get; set; }

        [Required(ErrorMessage = "Please enter your country")]
        [StringLength(50)]
        public string Country { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter your phone number")]
        [StringLength(25)]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone number")]
        public string PhoneNumber { get; set; } = string.Empty;

        [Required]
        [StringLength(50)]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|""(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*"")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])",
            ErrorMessage = "The email address is not entered in a correct format")]
        public string Email { get; set; } = string.Empty;

        [BindNever]
        public decimal OrderTotal { get; set; }

        [BindNever]
        public DateTime OrderPlaced { get; set; }
    }
}

Cakeful/Controllers/OrderController.cs
using Cakeful.Models;
using Cakeful.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Cakeful.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly IShoppingCart _shoppingCart;

        public OrderController(IOrderRepository orderRepository, IShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your cart is empty, please add some cakes into it first before checking out.");
            }
            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete");
            }
            return View(order);
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Order completed. Thank you for shopping at Cakeful! Your delicious cakes will be sent to you soon!";
            return View();
        }
    }
}

Cakeful/Controllers/ShoppingCartController.cs
using Cakeful.Repositories;
using Cakeful.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Cakeful.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCart _shoppingCart;
        private readonly ICakeRepository _cakeRepository;

        public ShoppingCartController(IShoppingCart shoppingCart, ICakeRepository cakeRepository)
        {
            _shoppingCart = shoppingCart;
            _cakeRepository = cakeRepository;
        }

        public IActionResult Index()
        {
            var shoppingCartItems = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = shoppingCartItems;
            var totalPrice = _shoppingCart.GetCartPrice();
            var shoppingCartViewModel = new ShoppingCartViewModel(shoppingCartItems, totalPrice);
            return View(shoppingCartViewModel);
        }

        public IActionResult AddToCart(int? cakeId)
        {
            var cakeToAdd = _cakeRepository.GetCake(cakeId);
            
            if (cakeToAdd == null)
            {
                return NotFound();
            }

            _shoppingCart.AddToCart(cakeToAdd);
            return RedirectToAction("Index");
        }
    }
}

Cakeful/Views/Order/Checkout.cshtml
@model Order

<a class="text-muted text-decoration-none" asp-controller="ShoppingCart" asp-action="Index">
    <i class="bi bi-arrow-left"></i>&nbsp;Back To Cart
</a>
<h1 class="text-center mt-3">You're Just One Step Away From Your Delicious Cakes!</h1>
<form method="post" asp-controller="Order" asp-action="Checkout" role="form">
    <div class="row mt-lg-4">
        <div class="col-12">
            <label asp-for="FirstName" class="form-label"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="col-12">
            <label asp-for="LastName" class="form-label"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
            
        <div class="col-12 mt-3">
            <label asp-for="AddressLine1" class="form-label"></label>
            <input asp-for="AddressLine1" class="form-control"/>
            <span asp-validation-for="AddressLine1" class="text-danger"></span>
        </div>
            
        <div class="col-12 mt-3">
            <label asp-for="AddressLine2" class="form-label"></label>
            <input asp-for="AddressLine2" class="form-control" />
            <span asp-validation-for="AddressLine2" class="text-danger"></span>
        </div>
            
        <div class="col-6 mt-3">
            <label asp-for="City" class="form-label"></label>
            <input asp-for="City" class="form-control" />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
            
        <div class="col-6 mt-3">
            <label asp-for="State" class="form-label"></label>
            <input asp-for="State" class="form-control" />
            <span asp-validation-for="State" class="text-danger"></span>
        </div>
            
        <div class="col-6 mt-3">
            <label asp-for="ZipCode" class="form-label"></label>
            <input asp-for="ZipCode" class="form-control" />
            <span asp-validation-for="ZipCode" class="text-danger"></span>
        </div>
            
        <div class="col-6 mt-3">
            <label asp-for="Country" class="form-label"></label>
            <input asp-for="Country" class="form-control" />
            <span asp-validation-for="Country" class="text-danger"></span>
        </div>
            
        <div class="col-12 mt-3">
            <label asp-for="Email" class="form-label"></label>
            <input asp-for="Email" class="form-control"/>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
            
        <div class="col-12 mt-3">
            <label asp-for="PhoneNumber" class="form-label"></label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="container mt-5 mb-lg-5">
            <input type="submit" asp-for="PhoneNumber" class="btn btn-success w-100" value="Complete Order"/>
        </div>
    </div>
    
</form>

Cakeful/Views/Order/CheckoutComplete.cshtml
<h3>
    @ViewBag.CheckoutCompleteMessage
</h3>